### ISSUE TITLE
Feature. Scheduled messages

### ISSUE THREAD

**Issue by velajos** [brianleect/basic-telegram-message#1]
Hi Brian, could you add the feature of sending messages every predefined period of time? 

It could be several messages, each with a user-defined time interval. 

For example:

Message 1 - sending every 2 hours 
Message 2 - sending every 4 hours 

And that these messages can be sent to several groups or channels at the same time. 

For example:

Telegram 01: 
Token id: xxx
Chat id: xxx

Telegram 02: 
Token id: xxx
Chat id: xxx

And so on for messages and recipients. 

Regards

**Comment by brianleect** [comment]
Hi @Juanjacinto123 ,

I have implemented the feature you have requested. Take note that the interval starts counting from the start of the program. I have implemented it with sleep between message intervals so it should not be especially intensive on CPU as well. Access the params.py file to add the respective token and chat_ids.

I have tested it to be working on my PC as well. Give it a shot and let me know if you face any issues.

**Comment by velajos** [comment]
> Hi @Juanjacinto123 ,
> 
> I have implemented the feature you have requested. Take note that the interval starts counting from the start of the program. I have implemented it with sleep between message intervals so it should not be especially intensive on CPU as well. Access the params.py file to add the respective token and chat_ids.
> 
> I have tested it to be working on my PC as well. Give it a shot and let me know if you face any issues.

Thank you very much. I will try and will be letting you know any updates

**Comment by velajos** [comment]
I also wanted to ask you if you know of any program or can be developed, which forwards messages from one channel to another Telegram channel. But with the conditions of forwarding every certain time and that allows to filter between the last messages of the channel. 

For example:

Forward the last 3 or 4 messages from channel A to channel B every 2 hours. But only if the messages to be forwarded have arrived to channel A during the last 5 minutes, that is to say that they are relatively recent. 

This is for forwarding recent news.

**Comment by brianleect** [comment]
> I also wanted to ask you if you know of any program or can be developed, which forwards messages from one channel to another Telegram channel. But with the conditions of forwarding every certain time and that allows to filter between the last messages of the channel.
> 
> For example:
> 
> Forward the last 3 or 4 messages from channel A to channel B every 2 hours. But only if the messages to be forwarded have arrived to channel A during the last 5 minutes, that is to say that they are relatively recent.
> 
> This is for forwarding recent news.

Could consider looking at https://github.com/MrMissx/Telegram_Forwarder

I'm not very familiar with implementing forwarding myself sadly.

**Comment by velajos** [comment]
> > I also wanted to ask you if you know of any program or can be developed, which forwards messages from one channel to another Telegram channel. But with the conditions of forwarding every certain time and that allows to filter between the last messages of the channel.
> > For example:
> > Forward the last 3 or 4 messages from channel A to channel B every 2 hours. But only if the messages to be forwarded have arrived to channel A during the last 5 minutes, that is to say that they are relatively recent.
> > This is for forwarding recent news.
> 
> Could consider looking at https://github.com/MrMissx/Telegram_Forwarder
> 
> I'm not very familiar with implementing forwarding myself sadly.

Thanks Brian, I will take a look

**Comment by brianleect** [comment]
Closing as feature has already been implemented. No updates on issues thus far.
